=== ELMERzark/Friflo.Json.Fliox/Json.Tests/assets~/Schema-Loop/JSON/EntityIdStore/UnitTest.Fliox.Client.EntityRefs.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$comment": "Generated by: https://github.com/friflo/Friflo.Json.Fliox/tree/main/Json/Fliox/Schema",
    "$ref": "#/definitions/EntityRefs",
    "definitions": {
        "EntityRefs": {
            "type": "object",
            "properties": {
                "id":              { "type": "string" },
                "guidEntity":      { "$ref": "./Standard.json#/definitions/Guid", "rel": "guidEntities" },
                "guidNullEntity":  { "oneOf": [{"type": "null"}, { "$ref": "./Standard.json#/definitions/Guid" }], "rel": "guidEntities" },
                "intEntity":       { "$ref": "./Standard.json#/definitions/int32", "rel": "intEntities" },
                "intNullEntity":   { "oneOf": [{"type": "null"}, { "$ref": "./Standard.json#/definitions/int32" }], "rel": "intEntities" },
                "intNullEntity2":  { "oneOf": [{"type": "null"}, { "$ref": "./Standard.json#/definitions/int32" }], "rel": "intEntities" },
                "longEntity":      { "$ref": "./Standard.json#/definitions/int64", "rel": "longEntities" },
                "longNullEntity":  { "oneOf": [{"type": "null"}, { "$ref": "./Standard.json#/definitions/int64" }], "rel": "longEntities" },
                "shortEntity":     { "$ref": "./Standard.json#/definitions/int16", "rel": "shortEntities" },
                "shortNullEntity": { "oneOf": [{"type": "null"}, { "$ref": "./Standard.json#/definitions/int16" }], "rel": "shortEntities" },
                "byteEntity":      { "$ref": "./Standard.json#/definitions/uint8", "rel": "byteEntities" },
                "byteNullEntity":  { "oneOf": [{"type": "null"}, { "$ref": "./Standard.json#/definitions/uint8" }], "rel": "byteEntities" },
                "customIdEntity":  { "type": ["string", "null"], "rel": "customIdEntities" },
                "intEntities":     { "type": ["array", "null"], "items": { "$ref": "./Standard.json#/definitions/int32" }, "rel": "intEntities" },
                "intNullEntities": { "type": ["array", "null"], "items": { "oneOf": [{ "type": "null"}, { "$ref": "./Standard.json#/definitions/int32" }]}, "rel": "intEntities" }
            },
            "required": [
                "id",
                "guidEntity",
                "intEntity",
                "longEntity",
                "shortEntity",
                "byteEntity"
            ],
            "additionalProperties": false
        }
    }
}

=== ELMERzark/Friflo.Json.Fliox/Json.Tests/assets~/Graph/EntityIdStore/EntityRefs/entity-ref-1.json
{
    "id": "entity-ref-1",
    "guidEntity": "11111111-1111-1111-1111-111111111111",
    "guidNullEntity": "22222222-2222-2222-2222-222222222222",
    "intEntity": 1234567890,
    "intNullEntity": null,
    "intNullEntity2": 1222222222,
    "longEntity": 1234567890123456789,
    "longNullEntity": null,
    "shortEntity": 12345,
    "shortNullEntity": null,
    "byteEntity": 123,
    "byteNullEntity": null,
    "customIdEntity": "abc",
    "intEntities": [
        1234567890
    ],
    "intNullEntities": [
        1234567890,
        null
    ]
}
