=== ELMERzark/Friflo.Json.Fliox/Json.Tests/assets~/Schema-Loop/JSON/PocStore/UnitTest.Fliox.Client.Order.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$comment": "Generated by: https://github.com/friflo/Friflo.Json.Fliox/tree/main/Json/Fliox/Schema",
    "$ref": "#/definitions/Order",
    "definitions": {
        "Order": {
            "type": "object",
            "description": "Some useful docs about an Order :). Test type reference '<b>OrderItem</b>'",
            "properties": {
                "id":       { "type": "string" },
                "customer": { "type": ["string", "null"], "relation": "customers", "description": "Some <b>useful</b> member documentation ðŸ™‚" },
                "created":  { "$ref": "./Standard.json#/definitions/DateTime" },
                "items":    { "type": ["array", "null"], "items": { "$ref": "./UnitTest.Fliox.Client.json#/definitions/OrderItem" } }
            },
            "required": [
                "id",
                "created"
            ],
            "additionalProperties": false
        }
    }
}

=== ELMERzark/Friflo.Json.Fliox/DemoHub/DB~/DemoStore/orders/00000001-4001-0000-0000-000000000000.json
{
    "id": "00000001-4001-0000-0000-000000000000",
    "customer": "00000001-2001-0000-0000-000000000000",
    "created": "2021-07-22T06:00:00.000Z",
    "items": [
        {
            "article": "00000001-1001-0000-0000-000000000000",
            "amount": 1,
            "name": "Camera"
        },
        {
            "article": "00000001-1002-0000-0000-000000000000",
            "amount": 2,
            "name": "Smartphone"
        },
        {
            "article": "00000001-1001-0000-0000-000000000000",
            "amount": 3,
            "name": "Camera"
        }
    ]
}
